### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by kmanjari** [brennanmcfarland/cartoon-gan#1]
Can you please provide me the dataset?

**Comment by brennanmcfarland** [comment]
The images are copyrighted so I can't distribute them to you directly, but here's a link to the web scraper I used to obtain them:
https://github.com/brennanmcfarland/keras/blob/master/cartoons/cartoon_web_scraper.py
python cartoon_web_scraper.py cartoonname yyyy-mm-dd yyyy-mm-dd
will grab a sample of images of the cartoon name you give it (which must match its name in the site's url) from the start date to the end date you provide it.  Feel free to fiddle with it, for example if you want to grab all the images instead of just some, but please use responsibly as I purposefully left it unoptimized to reduce the burden on the site (and out of laziness).  For my experiments I pretty much just used Calvin and Hobbes and Peanuts.  Enjoy!
